name: Build and Push IaC Toolbox

on:
    push:
        branches: [main]
    workflow_dispatch:

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        # This silences the deprecation warning and future-proofs the runner
        env:
            FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
            GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

        permissions:
            contents: read
            packages: write

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4 # Should now run on Node 24 via the env var

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Log in to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GH_TOKEN }}

            - name: Run Build and Push via Makefile
              run: |
                  make build
                  make push
